{"uuid": "9804febb-8b69-4569-b52f-a7375427e11b", "children": ["322ddd68-1e60-4756-b7d2-20b65fd81307"], "befores": [{"name": "cleanup_after_test", "status": "passed", "start": 1737654240116, "stop": 1737654240116}], "afters": [{"name": "cleanup_after_test::0", "status": "broken", "statusDetails": {"message": "Exception: No se pudo encontrar el botón Home usando los selectores disponibles.\n", "trace": "  File \"C:\\Users\\Augusto  Sanchez\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Augusto  Sanchez\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Augusto  Sanchez\\Desktop\\Testing Projects\\PWC-Challenge\\UI-Testing-Selenium-Python\\conftest.py\", line 39, in cleanup_after_test\n    base_page_obj.go_to_home()\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Augusto  Sanchez\\Desktop\\Testing Projects\\PWC-Challenge\\UI-Testing-Selenium-Python\\page\\base_page.py\", line 49, in go_to_home\n    raise Exception(\"No se pudo encontrar el botón Home usando los selectores disponibles.\")\n"}, "start": 1737654267000, "stop": 1737654343121}], "start": 1737654240116, "stop": 1737654343121}