{"uuid": "cbd07260-b4b4-4482-a6a5-d071b98fd875", "children": ["f2251ea0-229b-49e1-a651-44eb1cece45f"], "befores": [{"name": "cleanup_after_test", "status": "passed", "start": 1737653609621, "stop": 1737653609621}], "afters": [{"name": "cleanup_after_test::0", "status": "broken", "statusDetails": {"message": "Exception: No se pudo encontrar el botón Home usando los selectores disponibles.\n", "trace": "  File \"C:\\Users\\Augusto  Sanchez\\AppData\\Roaming\\Python\\Python313\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Augusto  Sanchez\\AppData\\Roaming\\Python\\Python313\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\Augusto  Sanchez\\Desktop\\Testing Projects\\PWC-Challenge\\UI-Testing-Selenium-Python\\conftest.py\", line 39, in cleanup_after_test\n    base_page_obj.go_to_home()\n    ~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\Augusto  Sanchez\\Desktop\\Testing Projects\\PWC-Challenge\\UI-Testing-Selenium-Python\\page\\base_page.py\", line 49, in go_to_home\n    raise Exception(\"No se pudo encontrar el botón Home usando los selectores disponibles.\")\n"}, "start": 1737653631179, "stop": 1737653679037}], "start": 1737653609621, "stop": 1737653679038}